### ISSUE TITLE
martinate MDP assumes a membrane even is there is none

### ISSUE THREAD

**Issue by jbarnoud** [Tsjerk/gromit#8]
martinate uses the $MEMBRANE variable to adapt its behaviour to the presence or not of a membrane. Yet, the variable is only defined very late in the script, long after it is used. As a result, MDP options that are dependant of the presence of a membrane are set like if there were a membrane, even when there is none.

**Comment by Tsjerk** [comment]
Fortunately, Gromacs can handle empty groups for TC. Effectively, the only result of this issue was that simulations were run with semi-isotropic pressure coupling, even if no membrane was present. That's not much of a problem. However, the check for membrane is now applied slightly differently, fixing this issue.
